config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root 'articles#index'
  
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  
  # resources :registrations 
  # resource :sessions
  resources :articles do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comments
  validates :commenter, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # binding.pry
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  
  def edit
    @article = Article.find(params[:id])
    @comment = Comment.find(params[:id])
  end

  def update
    # debugger
    # @article = Article.find(params[:id])

    @comment = Comment.find(params[:id])
    @comment.update(params[:comment])
    if @comment.update(comment_params)
        redirect_to @article
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<% if current_user.present? %>
<p>
    <%#debugger%>
    <li><%= link_to "Edit Comments", edit_article_comment_path(@article.comments) %></li>
</p> 
<%end%>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form", comment: @comment %>